### ISSUE TITLE
Fix address of gulp 4

### ISSUE THREAD

**Issue by gustawdaniel** [anges244/evie#5]
During installation there is error

```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git checkout 4.0
npm ERR! error: pathspec '4.0' did not match any file(s) known to git.
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2019-01-15T10_38_33_800Z-debug.log
```

Because of 

```
    "gulp": "git://github.com/gulpjs/gulp#4.0",
```

in `package.json`

**Comment by gustawdaniel** [comment]
Gulp 4 is released now.

Also tests does not works

```
npm run test
```

gives

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/daniel/.nvm/versions/node/v10.7.0/bin/node',
1 verbose cli   '/home/daniel/.nvm/versions/node/v10.7.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@6.1.0
3 info using node@v10.7.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle evie@0.2.12~pretest: evie@0.2.12
6 info lifecycle evie@0.2.12~test: evie@0.2.12
7 verbose lifecycle evie@0.2.12~test: unsafe-perm in lifecycle true
8 verbose lifecycle evie@0.2.12~test: PATH: /home/daniel/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/daniel/test/evie/node_modules/.bin:/home/daniel/.sdkman/candidates/gradle/current/bin:/home/daniel/.yarn/bin:/home/daniel/.config/yarn/global/node_modules/.bin:/home/daniel/.rakudobrew/bin:/home/daniel/perl5/bin:/home/daniel/.nvm/versions/node/v10.7.0/bin:/home/daniel/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
9 verbose lifecycle evie@0.2.12~test: CWD: /home/daniel/test/evie
10 silly lifecycle evie@0.2.12~test: Args: [ '-c', 'test' ]
11 silly lifecycle evie@0.2.12~test: Returned: code: 1  signal: null
12 info lifecycle evie@0.2.12~test: Failed to exec test script
13 verbose stack Error: evie@0.2.12 test: `test`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/daniel/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/daniel/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid evie@0.2.12
15 verbose cwd /home/daniel/test/evie
16 verbose Linux 4.15.0-43-generic
17 verbose argv "/home/daniel/.nvm/versions/node/v10.7.0/bin/node" "/home/daniel/.nvm/versions/node/v10.7.0/bin/npm" "run" "test"
18 verbose node v10.7.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error evie@0.2.12 test: `test`
22 error Exit status 1
23 error Failed at the evie@0.2.12 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

So I propose to remove it if tests are not implemented.

**Comment by anges244** [comment]
Sorry for being unresponsive for so long... Fixed the Gulp issue with the new address. I hadn't added tests and the command was just left there. Added the correct gulp tasks now... Thanks!
